version: "3.3"
services:
  site:
    depends_on:
      - db
    volumes:
       - D:\_dev\newdev\LaravelTest:/var/www/html
     # - /media/dob666/Main/_dev/newdev/LaravelTest:/var/www/html
       - D:\_dev\newdev\LaravelTest\apache2:/etc/apache2/sites-enabled
     # - /media/dob666/Main/_dev/newdev/LaravelTest/apache2:/etc/apache2/sites-enabled
       - C:\tmp:/tmp
     # - /tmp:/tmp
    build: .
    container_name: laravel
    ports:
      - 80:80
    links:
      - db
    restart: always
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  db:
    image: mysql:8.0
    restart: always
    container_name: db
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
    ports:
      - 3306:3306
    volumes:
      - D:\_dev\newdev\LaravelTest\mysql:/var/lib/mysql
     # - /media/dob666/Main/_dev/newdev/LaravelTest/mysql:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
